select * from prj2.dbo.supermarket_data


/*Total Sales done by each branch*/
select Branch, Sum(Total) AS total_sales
FROM prj2.dbo.supermarket_data
group by Branch
order by Sum(Total)
desc


/*Minimum Sales done by each branch*/
select Branch, min(Total) as minimum_sales
FROM prj2.dbo.supermarket_data
group by Branch
order by min(Total)
desc

/*Total Sales done in each City*/
select City, SUM(Total)
FROM prj2.dbo.supermarket_data
group by City

/*Maximum Sales done in each City*/
select City, max(Total)
FROM prj2.dbo.supermarket_data
group by City

/*Minimum Sales done in each City*/
select City, min(Total)
FROM prj2.dbo.supermarket_data
group by City

/*AVG Sales done by each Branch*/
select Branch, avg(Total)
FROM prj2.dbo.supermarket_data
group by Branch

/*AVG Sales done in each City*/
select City, avg(Total)
FROM prj2.dbo.supermarket_data
group by City

/*Maximum Sale Done By a Group according to Cities*/
SELECT City, Branch, Max(Total) AS Money_spent
FROM prj2.dbo.supermarket_data
group by City, Branch

/*Minimum Sale Done By a Group according to Cities*/
SELECT City, Branch, Min(Total) AS Money_spent
FROM prj2.dbo.supermarket_data
group by City, Branch

/*Maximum Money generated by Product lines*/
select max(Total), product_line
from prj2.dbo.supermarket_data
group by product_line

/*Maximum Money generated by Product lines according to Gender*/
select max(Total), product_line, Gender
from prj2.dbo.supermarket_data
Group by Gender, product_line
Order by  Gender, product_line

/*Minimum Money generated by Product lines according to Gender*/
select min(Total) AS Money_spent, product_line, Gender
from prj2.dbo.supermarket_data
Group by Gender, product_line
Order by  Gender, product_line

/*Average Money generated by Product lines according to Gender*/
select avg(Total) AS Money_spent, product_line, Gender
from prj2.dbo.supermarket_data
Group by Gender, product_line
Order by  Gender, product_line

/*Maximum Money generated by Product lines according to Gender in each City*/
select avg(Total) AS Money_spent, product_line, Gender, City
from prj2.dbo.supermarket_data
Group by Gender, product_line, City
Order by  Gender, product_line, City

/*Average rating given by each gender to a product line*/
select Round(Avg(rating), 1), product_line, Gender
from prj2.dbo.supermarket_data
group by product_line, Gender
order by product_line, Gender


/* Converting Time*/
select Time, convert(time, Time)
From prj2.dbo.supermarket_data

alter table prj2.dbo.supermarket_data
add Timeconverted time

update prj2.dbo.supermarket_data
set Timeconverted = convert(time, Time)

select Timeconverted from prj2.dbo.supermarket_data

/* Converting Date*/
select Date, convert(date, Date)
From prj2.dbo.supermarket_data

alter table prj2.dbo.supermarket_data
add Dateconverted date

update prj2.dbo.supermarket_data
set Dateconverted = convert(date, Date)

select Dateconverted from prj2.dbo.supermarket_data


select avg(Total) AS Money_Spent, Dateconverted
from prj2.dbo.supermarket_data
Group by Dateconverted
Order by  Dateconverted

/*calculating Monthly and Yearly Total*/
select year(Dateconverted), month(Dateconverted), sum(Total)
from prj2.dbo.supermarket_data
group by year(Dateconverted), month(Dateconverted)
order by year(Dateconverted), month(Dateconverted)


select * from prj2.dbo.supermarket_data

/*calculating Monthly and Yearly Total based on customer type*/
select year(Dateconverted), month(Dateconverted), sum(Total), [Customer type]
from prj2.dbo.supermarket_data
group by year(Dateconverted), month(Dateconverted), [Customer type]
order by year(Dateconverted), month(Dateconverted), [Customer type]

/*calculating how much a product line generated in a month in year 2019*/
select year(Dateconverted) AS Year, month(Dateconverted) AS Month, sum(Total) AS Sub_Total, product_line
from prj2.dbo.supermarket_data
group by year(Dateconverted), month(Dateconverted), product_line
order by year(Dateconverted), month(Dateconverted), product_line

/*calculating how much a specifc Payment method generated total cash made by sales*/

select (Payment), sum(Total) 
from prj2.dbo.supermarket_data
group by Payment
order by sum(Total)

select * from prj2.dbo.supermarket_data

/*Figuring out Product categories based on the total sales*/
select product_line, sum(Total)
from prj2.dbo.supermarket_data
group by product_line
order by sum(Total)
desc

/*Number of normal customer and members*/
select [Customer type], Gender, count(*)
from prj2.dbo.supermarket_data
group by [Customer type], Gender

/*Average quantity purchased above a given condition*/
select avg(Quantity)
from prj2.dbo.supermarket_data
where Total > 500

/*Average of Quantity*/
select avg(Quantity)
from prj2.dbo.supermarket_data

/*Sales made in between selected dates*/
select * from prj2.dbo.supermarket_data
where [Dateconverted] between '2019-02-01' and '2019-02-12'

/*Top 3 days where the sales were the highest*/

select top 3 Dateconverted, sum(Total)
from prj2.dbo.supermarket_data
group by Dateconverted
order by sum(Total)
desc

/*Highest sale date*/

select Dateconverted
from prj2.dbo.supermarket_data
where Total = (select max(Total)from prj2.dbo.supermarket_data)

/*How many sales according to a day where the sales were the highest?*/
select count(*)
from prj2.dbo.supermarket_data
where Dateconverted = (select Dateconverted from prj2.dbo.supermarket_data where Total = (select max(Total) from prj2.dbo.supermarket_data))

/*Average sale done to Customer type in regards to branches*/
select branch, [Customer type], avg(total)
from prj2.dbo.supermarket_data
group by branch, [Customer type]
order by avg(total) desc;

/*Total Quantity sold of products in a Product line*/
select product_line, sum(quantity) 
from prj2.dbo.supermarket_data
group by product_line
order by sum(quantity) desc

/*Difference of unit price in a particular Product line*/
select max(unit_price) - min(unit_price) as diff
from prj2.dbo.supermarket_data
where product_line = 'Health and beauty'

/*Difference of unit prices of all Product line*/
select product_line, max(unit_price) - min(unit_price) as diff
from prj2.dbo.supermarket_data
group by product_line

